server:
  port: 8080

caiyun:
  token: xxxxxxxxxxxxxxxxx

feishu:
  webhook: "https://open.feishu.cn/open-apis/bot/v2/hook/xxxxxxxxxxxxxxxxx"

cities:
  - name: "北京"
    lng: 116.4074
    lat: 39.9042

  - name: "上海"
    lng: 121.4737
    lat: 31.2304

database:
  host: 127.0.0.1
  port: 3306
  username: weather
  password: xxxxxxx
  database: weather
  charset: utf8mb4
